// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWeb.Data;

#nullable disable

namespace MovieWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230809194922_AddingDataToTHeTable")]
    partial class AddingDataToTHeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieWeb.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An interesting movie",
                            Title = "Oppenheimer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An interesting movie",
                            Title = "Barbie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An interesting movie",
                            Title = "Home Alone"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An interesting movie",
                            Title = "Harry Potter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
